version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
      
  frontend:
    build: ./client
    ports:
      - "4200:4200"
    depends_on:
      - backend

  mysql_db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: websocket-chat
    restart: always