version: '3.8'

services:
  app-server:
    build: ./server
    ports:
      - "8080:8080"
    environment: 
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/websocket-chat?allowPublicKeyRetrieval=true&useSSL=false
        SPRING_DATASOURCE_USERNAME: user
        SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql_db
      
  app-client:
    build: ./client
    ports:
      - "4200:4200"
    depends_on:
      - app-server
      
  mysql_db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: websocket-chat
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    restart: always