spring:
  datasource:
    username: "root"
    password: "patryk"
    url: "jdbc:mysql://database:3306/websocket-chat"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop